services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - sqlite_data:/app/storage
    ports:
      - "3000:3000"
      - "1234:1234" # Debug port for ruby_lsp
    environment:
      RAILS_ENV: development
      DOCKER: "true"

volumes:
  sqlite_data:
  node_modules:
