FROM ruby:3.2

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
  apt-get update -qq && apt-get install -y \
  build-essential \
  nodejs && \
  npm install -g yarn

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN gem install bundler foreman && bundle install

COPY package.json ./

RUN yarn install --no-lockfile

COPY . .

RUN chmod +x entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["./entrypoint.sh"]
CMD ["bin/dev"]
